/* ============================================================
   nav-tiles.js — source unique du bloc de navigation en tuiles
   (GIF rouge et blanc, grille de tuiles groupées, logo de pied), partagé
   par les 24 pages qui le portaient chacune à la main, par le gabarit des
   64 hexagrammes (generate-hexagram-pages.js), et bientôt par les pages de
   motifs.

   Même principe que scripts/langues.js pour le hreflang : une liste, un
   rendu par page avec auto-exclusion (une page ne se lie pas à elle-même),
   pas de copie. Voir scripts/build-header.js pour le point de câblage
   (zone @navtiles) et data/motifs-pinterest/prompt-cc-bas-de-page*.md dans
   Downloads pour la décision d'origine.

   Huit langues depuis le 2026-10-04 (décision d'Anibal : les tuiles sur
   toutes les pages du site, dans la langue de la page). Le français et
   l'anglais sont ici ; es, th, zh, ru, pt, hi viennent de
   scripts/nav-tiles-libelles.js, chaque texte avec sa provenance.

   Les ADRESSES suivent la langue de la page quand la page traduite existe :
   la tuile « Accueil » d'une page espagnole mène à /es/, « Lexique » à
   /es/lexico/… La correspondance n'est pas tenue ici : elle est lue dans les
   groupes de traduction de scripts/langues.js, ceux qui écrivent déjà les
   hreflang — une tuile qui renverrait au français depuis une page thaïe
   serait la même asymétrie que la régression hreflang de #137. Là où la page
   traduite n'existe pas, la tuile garde l'adresse française ;
   sansTraduction() en donne la liste par langue.
   ============================================================ */

const { LANGUES, GROUPES: GROUPES_LANGUES, annonceVers, espaceAvant } = require('./langues.js');
const I18N = require('./nav-tiles-libelles.js');

// Cinq catégories (prompt-navigation.md, 2026-10-05) : les 19 tuiles à plat
// ne se lisaient plus — à ce nombre on balaye, on ne choisit plus. Elles
// remplacent les quatre groupes d'avant (Créer, Explorer, Lire, Le projet).
// « Galeries » est une catégorie à part, pas un rangement sous l'outil
// correspondant : un visiteur qui arrive par un reel cherche à voir, pas à
// fabriquer (décision d'Anibal). Les six autres langues sont dans
// nav-tiles-libelles.js (CATEGORIES_I18N), avec leur provenance.
const CATEGORIES = [
  { id: 'galeries', fr: 'Galeries', en: 'Galleries' },
  { id: 'animations', fr: 'Animations', en: 'Animations' },
  { id: 'tirages', fr: 'Tirages', en: 'Draws &amp; prints' },
  { id: 'outils-creatifs', fr: 'Outils créatifs', en: 'Creative tools' },
  { id: 'a-propos-du-projet', fr: 'À propos du projet', en: 'About the project' },
];

// Les 24 destinations rangées. « categories » : la PREMIÈRE est la catégorie
// principale — celle qui s'ouvre quand on est sur la page, et la seule où
// l'entrée est marquée ; les suivantes portent un lien ordinaire. Une page
// peut figurer dans deux catégories (« deux liens valent mieux qu'un »,
// Anibal, pour galerie-animations), jamais dans zéro, et n'a qu'une
// principale — ce que la forme des données garantit.
// Libellés « Galerie tricolore » / « Magic quadricolore » / « Le traité » :
// voir prompt-cc-nommage-galeries.md et prompt-cc-renommage-quadricolore.md.
// Les descriptions sont celles des tuiles d'avant, conservées telles quelles ;
// les sept pages qui n'avaient pas de tuile ont la leur, tirée de leur page.
const TUILES = [
  { id: 'galerie-animations', href: 'galerie-animations.html', categories: ['galeries', 'animations'],
    fr: { label: "Galerie d'animations", excerpt: 'Les animations des collections de fonds, en six groupes : à regarder, à prévisualiser, à télécharger en MP4.' },
    en: { label: 'Animation gallery', excerpt: 'The animations of the ground collections, in six groups: to watch, preview and download as MP4.' } },
  { id: 'galerie-bicolore', href: 'galerie-bicolore.html', categories: ['galeries'],
    fr: { label: 'Galerie bicolore', excerpt: '142 motifs bicolores engendrés par les axes et fermés sur le cube — maille, pavage, export.' },
    en: { label: 'Two-colour gallery', excerpt: '142 two-colour patterns generated by the axes and closed on the cube — grain, tiling, export.' } },
  { id: 'galerie-tricolore', href: 'galerie-patterns-unifies.html', categories: ['galeries'],
    fr: { label: 'Galerie tricolore', excerpt: 'Patterns unifiés, engendrés par mélange de teintes — sélectionnez un motif pour voir son pavage.' },
    en: { label: 'Three-colour gallery', excerpt: 'Unified patterns, generated by tint mixing — select a motif to see its tiling.' } },

  { id: 'fonds-ecran', href: 'fonds-ecran.html', categories: ['animations'],
    fr: { label: "Fond d'écran", excerpt: "Fonds d'écran textiles plein écran, réactifs au son ou en mode méditatif à rythme réglable." },
    en: { label: 'Wallpapers', excerpt: 'Full-screen textile wallpapers, sound-reactive or at an adjustable meditative pace.' } },

  { id: 'tirage', href: 'tirage-livree-hermes.html', categories: ['tirages'],
    fr: { label: 'Tirage du Yi King', excerpt: "Tirez un hexagramme au hasard et découvrez son carré, ou parcourez l'échiquier des 64 mutations." },
    en: { label: 'Yi King draw', excerpt: 'Draw a hexagram at random and discover its square, or browse the chessboard of the 64 changes.' } },
  { id: 'impression', href: '360-calques.html', categories: ['tirages'],
    fr: { label: '360 calques', excerpt: "Tirez et téléchargez les calques d'impression, prêts à imprimer." },
    en: { label: '360 layers', excerpt: 'Draw and download print-ready layers.' } },
  { id: 'motifs-svg', href: 'telechargements.html', categories: ['tirages'],
    fr: { label: 'Motifs SVG', excerpt: 'Téléchargez les calques d\'impression en 4 catégories de combinaisons de traits, au format SVG.' },
    en: { label: 'SVG patterns', excerpt: 'Download the print layers in 4 categories of trait combinations, as SVG.' } },
  { id: 'hexagrammes', href: 'hexagrammes/', categories: ['tirages'],
    fr: { label: 'Hexagrammes', excerpt: 'Les 64 hexagrammes du Yi-King : jugement, trigrammes et carré magique pour chacun.' },
    en: { label: 'Hexagrams', excerpt: 'The 64 hexagrams of the Yi King: judgment, trigrams and magic square for each.' } },

  { id: 'creation-motifs', href: 'creation-motifs-yi-king.html', categories: ['outils-creatifs'],
    fr: { label: 'Créer un motif', excerpt: 'Composez vos propres motifs textiles à partir des 60 images du Yi King.' },
    en: { label: 'Create a pattern', excerpt: 'Compose your own textile patterns from the 60 images of the Yi King.' } },
  { id: 'bicolore', href: 'bicolore.html', categories: ['outils-creatifs'],
    fr: { label: 'Motifs bicolores', excerpt: 'Composez une cellule 12×12, six niveaux, chacun sa famille et sa teinte.' },
    en: { label: 'Two-colour patterns', excerpt: 'Compose a 12×12 cell, six levels, each with its own family and tint.' } },
  { id: 'bicolore-v2', href: 'creation-bicolore-v2.html', categories: ['outils-creatifs'],
    fr: { label: 'Motifs bicolores v2', excerpt: 'La seconde découpe des diagonales (YA/AY), vocabulaire et statuts du demi-décalage — à côté de l’outil v1.' },
    en: { label: 'Two-colour patterns v2', excerpt: 'The second diagonal split (YA/AY), vocabulary and half-shift statuses — alongside the v1 tool.' } },
  { id: 'encodeur', href: 'encodeur.html', categories: ['outils-creatifs'],
    fr: { label: 'Encodeur', excerpt: 'Encodage stéganographique géométrique par double référent, croix ansée et Jacquard.' },
    en: { label: 'Encoder', excerpt: 'Geometric steganographic encoding by double referent, ansate cross and Jacquard.' } },
  { id: 'carter-demo', href: 'carter-demo.html', categories: ['outils-creatifs'],
    fr: { label: 'Carter Random', excerpt: 'Démo interactive : la grille et les référents dérivés de la clé.' },
    en: { label: 'Carter Random', excerpt: 'Interactive demo: the grid and the referents derived from the key.' } },
  { id: 'quadricolore', href: 'unified-patterns.html', categories: ['outils-creatifs'],
    fr: { label: 'Magic quadricolore', excerpt: 'Les 64 motifs des hexagrammes, personnalisables et téléchargeables en haute résolution.' },
    en: { label: 'Magic quadricolore', excerpt: 'The 64 hexagram patterns, customisable and downloadable in high resolution.' } },
  { id: 'cymatique', href: 'cymatique.html', categories: ['outils-creatifs'],
    fr: { label: 'Cymatique', excerpt: 'Le pavage dont la fréquence spatiale se rapproche le plus du son que vous émettez.' },
    en: { label: 'Cymatics', excerpt: 'The tiling whose spatial frequency comes closest to the sound you make.' } },
  { id: 'outils', href: 'outils.html', categories: ['outils-creatifs'],
    fr: { label: 'Outils', excerpt: 'Tous les outils interactifs du site, réunis en un seul endroit.' },
    en: { label: 'Tools', excerpt: 'All the site\'s interactive tools, gathered in one place.' } },

  { id: 'traite', href: 'la-livree-d-hermes.html', categories: ['a-propos-du-projet'],
    fr: { label: 'Le traité', excerpt: 'Le traité et ses éditions traduites, les hexagrammes et le lexique.' },
    en: { label: 'The treatise', excerpt: 'The treatise and its translated editions, the hexagrams and the lexicon.' } },
  { id: 'a-propos', href: 'a-propos.html', categories: ['a-propos-du-projet'],
    fr: { label: 'À propos', excerpt: "L'auteur et son livre, au croisement de la philosophie, des mathématiques et des sciences appliquées." },
    en: { label: 'About', excerpt: 'The author and his book, at the crossing of philosophy, mathematics and applied science.' } },
  { id: 'lexique', href: 'lexique.html', categories: ['a-propos-du-projet'],
    fr: { label: 'Lexique', excerpt: "Dix notions clés pour comprendre La Livrée d'Hermès." },
    en: { label: 'Lexicon', excerpt: "Ten key notions for understanding La Livrée d'Hermès." } },
  { id: 'profil', href: 'profil.html', categories: ['a-propos-du-projet'],
    fr: { label: 'Profil documentaire', excerpt: "Brevets et 63 dessins et modèles déposés à l'INPI, couvrant les carrés d'ordre 12." },
    en: { label: 'Documentary profile', excerpt: 'Patents and 63 designs registered with the INPI, covering the order-12 squares.' } },
  { id: 'contact', href: 'contact.html', categories: ['a-propos-du-projet'],
    fr: { label: 'Contact', excerpt: 'Contactez l\'auteur pour un projet ou une commande de motifs et tirages textiles.' },
    en: { label: 'Contact', excerpt: 'Contact the author for a project or a commission of patterns and textile prints.' } },
  { id: 'soutien', href: 'soutenir.html', categories: ['a-propos-du-projet'],
    fr: { label: 'Soutenir', excerpt: "Soutenir La Livrée d'Hermès à prix libre : le site et son contenu restent gratuits." },
    en: { label: 'Support', excerpt: "Support La Livrée d'Hermès at a price you choose: the site and its content stay free." } },
  { id: 'chiffres', href: 'chiffres-et-sources.html', categories: ['a-propos-du-projet'],
    fr: { label: 'Chiffres et sources', excerpt: "Chaque chiffre du site, le script qui le reproduit et la ligne qu'il imprime." },
    en: { label: 'Figures and sources', excerpt: 'Every figure on the site, the script that reproduces it and the line it prints.' } },
  { id: 'travaux', href: 'travaux.html', categories: ['a-propos-du-projet'],
    fr: { label: 'Travaux', excerpt: 'Les dépôts, le code et les articles soumis, chacun horodaté et ouvert.' },
    en: { label: 'Works', excerpt: 'Deposits, code and submitted papers, each one timestamped and open.' } },
];

// Hors des catégories, deux liens fixes au-dessus du bloc : l'accueil (« ce
// n'est pas une destination parmi d'autres, c'est le retour » —
// prompt-cc-fragment-retours.md §4) et les articles, qui seraient seuls dans
// leur catégorie — une catégorie d'un élément fait cliquer deux fois pour un
// lien (prompt-navigation.md). Ils gardent leur icône.
const ACCUEIL = {
  id: 'accueil', href: 'index.html', icon: 'accueil',
  fr: { label: 'Accueil', excerpt: "Le livre, ses planches et l'ensemble des outils." },
  en: { label: 'Home', excerpt: "The book, its plates and the full set of tools." },
};
const ARTICLES = {
  id: 'articles', href: 'articles.html', icon: 'articles',
  fr: { label: 'Articles', excerpt: "Réflexions et recherches autour de La Livrée d'Hermès." },
  en: { label: 'Articles', excerpt: "Reflections and research around La Livrée d'Hermès." },
};
const FIXES = [ACCUEIL, ARTICLES];

// Les six autres langues, fusionnées depuis nav-tiles-libelles.js.
for (const c of CATEGORIES) {
  if (!I18N.CATEGORIES_I18N[c.id]) throw new Error(`nav-tiles-libelles.js : pas de nom pour la catégorie ${c.id}`);
  Object.assign(c, I18N.CATEGORIES_I18N[c.id]);
}
for (const t of [...TUILES, ARTICLES]) {
  if (!I18N.TUILES_I18N[t.id]) throw new Error(`nav-tiles-libelles.js : pas de textes pour la tuile ${t.id}`);
  Object.assign(t, I18N.TUILES_I18N[t.id]);
}
Object.assign(ACCUEIL, I18N.ACCUEIL_I18N);

// Le groupe de traduction (scripts/langues.js) d'une destination : celui qui
// contient son adresse française, sauf le traité, dont les jumelles sont les
// pages du livre de chaque langue (/en/book/, /es/libro/…).
const GROUPE_DE_TUILE = { traite: 'livre' };
function fichierDe(href) { return href.endsWith('/') ? `${href}index.html` : href; }
function adresseLocale(id, href, lang) {
  if (lang === 'fr') return href;
  const groupe = GROUPE_DE_TUILE[id]
    ? GROUPES_LANGUES.find((g) => g.nom === GROUPE_DE_TUILE[id])
    : GROUPES_LANGUES.find((g) => g.pages.some((p) => p[2] === fichierDe(href)));
  const page = groupe && groupe.pages.find((p) => p[0] === lang);
  return page ? page[2].replace(/index\.html$/, '') : null;
}
// Par langue, les destinations qui n'ont pas de page traduite : la tuile y
// garde l'adresse française.
function sansTraduction() {
  const out = {};
  for (const lang of Object.keys(LANGUES)) {
    out[lang] = [...FIXES, ...TUILES].filter((t) => adresseLocale(t.id, t.href, lang) === null).map((t) => t.id);
  }
  return out;
}

// Les refus : un id en double, une catégorie inconnue, une entrée sans
// catégorie ou deux fois dans la même, une catégorie vide, un compte qui
// dérive (24 entrées rangées + 2 liens fixes = les 26 pages du bloc).
const IDS_CATEGORIES = new Set(CATEGORIES.map((c) => c.id));
if (new Set([...FIXES, ...TUILES].map((t) => t.id)).size !== TUILES.length + FIXES.length) {
  throw new Error('nav-tiles.js : id de tuile en double.');
}
for (const t of TUILES) {
  if (!t.categories || !t.categories.length) throw new Error(`nav-tiles.js : ${t.id} n'a aucune catégorie.`);
  if (new Set(t.categories).size !== t.categories.length) throw new Error(`nav-tiles.js : ${t.id} figure deux fois dans la même catégorie.`);
  for (const c of t.categories) if (!IDS_CATEGORIES.has(c)) throw new Error(`nav-tiles.js : ${t.id} dans une catégorie inconnue « ${c} ».`);
}
for (const c of CATEGORIES) if (!TUILES.some((t) => t.categories.includes(c.id))) throw new Error(`nav-tiles.js : catégorie ${c.id} vide.`);
if (TUILES.length + FIXES.length !== 26) {
  throw new Error(`nav-tiles.js : ${TUILES.length} entrées rangées et ${FIXES.length} liens fixes, 26 pages attendues.`);
}

// Les pages qui ne sont pas l'une des 26 mais en dépendent : la catégorie de
// leur page parente s'ouvre, sans qu'aucune entrée soit marquée (on n'est pas
// SUR la page parente). Les hexagrammes de chaque langue, les pages de groupe
// de la galerie d'animations, les pages du livre et leurs chapitres, les
// articles (lien fixe : rien ne s'ouvre).
const GALERIE = require('../data/galerie-animations.json');
function parenteDe(rel) {
  if (/^(hexagrammes|en\/hexagrams|es\/hexagramas|th\/hexagrams)\//.test(rel)) return 'hexagrammes';
  for (const [l, a] of Object.entries(GALERIE.adresses)) {
    if (!a.groupe) continue;
    const dossier = a.groupe.split('{slug}')[0];
    if (rel.startsWith(dossier) || rel === a.entree || rel === `${a.entree}index.html`) return 'galerie-animations';
  }
  const livre = GROUPES_LANGUES.find((g) => g.nom === 'livre');
  if (livre && livre.pages.some((p) => rel.startsWith(p[2].replace(/index\.html$/, '')))) return 'traite';
  if (/^(en\/)?articles\//.test(rel)) return 'articles';
  return null;
}

/* rel : chemin du fichier courant depuis la racine du dépôt, séparateurs `/`
   (voir scripts/build-header.js pour la normalisation). prefixe : déjà
   calculé par build-header.js (même variable, pas recalculée ici — c'est le
   seul moyen d'être certain de ne jamais diverger de son propre calcul, y
   compris son cas spécial 404.html).
   Rend les deux liens fixes et les catégories, chaque entrée avec son
   adresse dans la langue de la page ; « courante » : l'entrée qui EST la page
   (marquée, sa catégorie principale ouverte) ; « ouverte » : la catégorie
   qui s'ouvre (celle de la page, ou de sa page parente). */
function tuilesPourPage(rel, prefixe, lang = 'fr') {
  const relDir = rel.endsWith('/index.html') ? rel.slice(0, -'index.html'.length) : rel;
  const estSoi = (href) => href === rel || href === relDir;
  const avecAdresse = (t) => {
    const href = adresseLocale(t.id, t.href, lang) ?? t.href;
    // la page n'existe pas dans la langue : la tuile le dit avant le clic
    return { ...t, finalHref: prefixe + href, courante: estSoi(href) || estSoi(t.href), annonce: annonceVers(href, lang) };
  };
  const fixes = FIXES.map(avecAdresse);
  const entrees = TUILES.map(avecAdresse);
  const courante = [...fixes, ...entrees].find((t) => t.courante);
  let ouverte = null;
  if (courante && courante.categories) ouverte = courante.categories[0];
  if (!courante) {
    const parente = parenteDe(rel);
    const t = parente && TUILES.find((x) => x.id === parente);
    if (t) ouverte = t.categories[0];
  }
  const categories = CATEGORIES.map((c) => ({
    ...c,
    ouverte: c.id === ouverte,
    entrees: entrees.filter((t) => t.categories.includes(c.id))
      .map((t) => ({ ...t, marquee: t.courante && t.categories[0] === c.id })),
  }));

  // Assertion bruyante : jamais deux entrées de la même catégorie vers la
  // même adresse, et au plus une entrée marquée dans tout le bloc. Même piège
  // que #130 (chemin relatif), même parade (échec net, pas un avertissement).
  for (const c of categories) {
    const hrefs = c.entrees.map((i) => i.finalHref);
    if (new Set(hrefs).size !== hrefs.length) throw new Error(`nav-tiles.js : adresses en double dans ${c.id} pour ${rel} : ${hrefs.join(', ')}`);
  }
  const marquees = categories.flatMap((c) => c.entrees.filter((t) => t.marquee)).length + fixes.filter((t) => t.courante).length;
  if (marquees > 1) throw new Error(`nav-tiles.js : ${marquees} entrées marquées pour ${rel}.`);
  return { fixes, categories };
}

// Icônes qui restent animées en permanence (comme le logo de tête) plutôt que
// de suivre la règle commune « PNG fixe, CSS au survol » — décision d'Anibal :
// seuls le logo de tête et l'icône bicolore gardent leur GIF actif hors
// survol. Les deux tuiles bicolores (l'outil, la galerie) en font partie —
// chacune avec son propre GIF, dessiné depuis ses propres données réelles.
const ICONES_TOUJOURS_ANIMEES = new Set(['bicolore', 'galerie-bicolore']);

// L'annonce d'une page dans une autre langue (scripts/langues.js, annonceVers).
const hreflangDe = (t) => (t.annonce ? ` hreflang="${t.annonce.hreflang}"` : '');
const marqueDe = (t) => (t.annonce ? `${espaceAvant(t.annonce.texte)}<span class="lien-langue">${t.annonce.texte}</span>` : '');

function htmlTuile(item, prefixe, lang) {
  const texte = item[lang] || item.fr;
  // GIF animé : première image fixe si le visiteur demande moins de mouvement.
  const img = ICONES_TOUJOURS_ANIMEES.has(item.icon)
    ? `<picture><source srcset="${prefixe}assets/nav-icons/${item.icon}-fixe.png" media="(prefers-reduced-motion: reduce)"><img class="nav-tile-icon" src="${prefixe}assets/nav-icons/${item.icon}-hover.gif" alt="" width="72" height="72" loading="lazy"></picture>`
    : `<img class="nav-tile-icon" src="${prefixe}assets/nav-icons/${item.icon}.png" alt="" width="72" height="72" loading="lazy">`;
  return `<a class="nav-tile" href="${item.finalHref}"${hreflangDe(item)}${item.courante ? ' aria-current="page"' : ''}>${img}<span class="nav-tile-body"><span class="nav-tile-label">${texte.label}${marqueDe(item)}</span><span class="nav-tile-excerpt">${texte.excerpt}</span></span></a>`;
}

// Une entrée de catégorie : le titre de la page, et sa phrase en dessous —
// sans icône (24 images de moins par page, sur 655 pages).
function htmlEntree(t, lang) {
  const texte = t[lang] || t.fr;
  return `<li><a href="${t.finalHref}"${hreflangDe(t)}${t.marquee ? ' aria-current="page"' : ''}><span class="nav-cat-label">${texte.label}${marqueDe(t)}</span><span class="nav-cat-texte">${texte.excerpt}</span></a></li>`;
}
// Une catégorie : un <details> natif, sans JavaScript — les liens restent dans
// le HTML, repliés ou non ; le nombre de pages à droite du titre.
function htmlCategorie(c, lang) {
  return `<details class="nav-cat"${c.ouverte ? ' open' : ''}>\n`
    + `        <summary><span class="nav-cat-titre">${c[lang] || c.fr}</span><span class="nav-cat-nombre">${c.entrees.length}</span></summary>\n`
    + `        <ul>\n          ${c.entrees.map((t) => htmlEntree(t, lang)).join('\n          ')}\n        </ul>\n`
    + `      </details>`;
}

// Le nom du bloc pour les lecteurs d'écran (<nav aria-label>).
const NAV_LABEL = { fr: 'Pages du site', en: 'Site pages', ...I18N.NAV_LABEL_I18N };

const SOUTIEN_BTN = {
  fr: { label: 'Devenir Soutien', title: "Soutenez la Livrée d'Hermès à prix libre : tout reste libre sous CC BY-NC 4.0, votre soutien finance la suite du projet." },
  en: { label: 'Become a Supporter', title: "Support La Livrée d'Hermès at a price you choose: everything stays free under CC BY-NC 4.0; your support funds the project's future." },
};
Object.assign(SOUTIEN_BTN, I18N.SOUTIEN_BTN_I18N);
const CREDIT_COLLAB = { fr: 'Créé en collaboration avec Claude', en: 'Created in collaboration with Claude', ...I18N.CREDIT_COLLAB_I18N };
const COPYRIGHT_SUFFIX = { fr: 'CC BY-NC 4.0', en: 'CC BY-NC 4.0', ...I18N.COPYRIGHT_SUFFIX_I18N };
// Le bouton Soutien mène à la page de soutien de la langue quand elle existe.
const SOUTIEN_HREF = (lang) => `https://anibal-amiot.com/${adresseLocale('soutien', 'soutenir.html', lang) ?? 'soutenir.html'}`;
const SOUTIEN_ANNONCE = (lang) => annonceVers(adresseLocale('soutien', 'soutenir.html', lang) ?? 'soutenir.html', lang);

/* Rend le bloc <div class="note">...</div> complet pour une page : les deux
   liens fixes (Accueil, Articles) au-dessus, hors des catégories ; le
   caducée et le bouton Devenir Soutien ; les cinq catégories ; puis le logo
   de pied, la ligne de crédit et le mot-symbole. */
function htmlNavTiles(rel, prefixe, lang = 'fr', seulementTuiles = false) {
  const { fixes, categories } = tuilesPourPage(rel, prefixe, lang);
  const blocFixes = `<div class="nav-tiles nav-tiles-accueil nav-fixes">\n      ${fixes.map((t) => htmlTuile(t, prefixe, lang)).join('\n      ')}\n    </div>`;
  const blocCategories = `<nav class="nav-categories" aria-label="${(NAV_LABEL[lang] || NAV_LABEL.fr)}">\n      ${categories.map((c) => htmlCategorie(c, lang)).join('\n      ')}\n    </nav>`;

  // Les pages traduites à la main gardent leur propre pied (bouton Soutien,
  // rangée de liens, crédit, logo) : elles ne reçoivent que les liens et les
  // catégories, posés avant lui — rien de ce qu'elles portent ne disparaît.
  if (seulementTuiles) {
    return `<div class="note note-tuiles">
    ${blocFixes}

    ${blocCategories}
  </div>`;
  }

  const soutien = SOUTIEN_BTN[lang] || SOUTIEN_BTN.fr;
  const collab = CREDIT_COLLAB[lang] || CREDIT_COLLAB.fr;
  const droits = COPYRIGHT_SUFFIX[lang] || COPYRIGHT_SUFFIX.fr;

  return `<div class="note">
    ${blocFixes}

    <div class="footer-caduceus">
      <picture><source srcset="${prefixe}assets/logo-caducee-fixe.png" media="(prefers-reduced-motion: reduce)"><img src="${prefixe}assets/logo-caducee.gif" alt="La Livrée d'Hermès" width="420" height="594" loading="lazy"></picture>
    </div>
    <a class="site-nav-btn" href="${SOUTIEN_HREF(lang)}"${hreflangDe({ annonce: SOUTIEN_ANNONCE(lang) })} style="display:inline-block; margin:14px 0;" title="${soutien.title}">${soutien.label}${marqueDe({ annonce: SOUTIEN_ANNONCE(lang) })}</a>

    ${blocCategories}

    <div class="center-logo-slot center-logo-slot-bottom">
      <picture><source srcset="${prefixe}assets/logo-static-fixe.png" media="(prefers-reduced-motion: reduce)"><img src="${prefixe}assets/logo-static.gif" alt="La Livrée d'Hermès" width="176" height="176" loading="lazy"></picture>
    </div>

    <div class="credit-line">
      <span>© <span id="credit-year">2026</span> Anibal Edelberto Amiot — ${droits}</span>
      <span class="credit-sep">·</span>
      <span>${collab}</span>
    </div>

    <div class="footer-title-logo">
      <img src="${prefixe}assets/title-logo-footer.png" alt="La Livrée d'Hermès" width="264" height="65" loading="lazy">
    </div>
  </div>`;
}

// Les pages qui ne reçoivent PAS le bloc de tuiles, avec leur raison. Lue par
// scripts/build-header.js et par tools/check_tuiles.mjs : une seule liste.
const SANS_TUILES = new Set([
  // carter-demo.html porte sa palette propre (--bg:#0a0e14, --gold:#c8aa6e) et
  // ne charge pas style.css (voir ce fichier) : lui donner une copie locale du
  // CSS des tuiles recréerait la divergence qu'on vient de supprimer. Elle
  // garde son petit pied universel, pas le bloc de tuiles.
  'carter-demo.html',
  // La visionneuse du livre est une application plein écran (hors sitemap) :
  // un bloc de tuiles sous elle se lirait comme une page cassée.
  'book-viewer/index.html',
]);

module.exports = { CATEGORIES, TUILES, FIXES, ACCUEIL, ARTICLES, tuilesPourPage, htmlNavTiles, sansTraduction, parenteDe, SANS_TUILES };
